name: "Rust builds"
description: "Builds and tests rust code"
inputs:
    toolchain:
        required: true
        description: "the Rust toolchain to use"

runs:
    using: "composite"
    steps:
        - uses: dtolnay/rust-toolchain@master
          with:
              toolchain: ${{ inputs.toolchain }}
        - uses: Swatinem/rust-cache@v2
        - name: Build
          shell: bash
          env:
              RUSTFLAGS: "--cfg tokio_unstable"
          run: |
              if [ "${{ inputs.toolchain }}" != stable ]; then
                  rm -fv Cargo.lock
              fi
              cargo build
        - name: Enable perf_event_open for tests
          shell: bash
          run: |
              sudo sysctl kernel.perf_event_paranoid=1
              cat /proc/sys/kernel/perf_event_paranoid
        - name: Run tests
          shell: bash
          env:
              RUSTFLAGS: "--cfg tokio_unstable"
          run: cargo test
